<?php

namespace AppBundle\Repository;

/**
 * EmailConfirmTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailConfirmTokensRepository extends \Doctrine\ORM\EntityRepository
{
}
