<?php

namespace AppBundle\Repository;

/**
 * WorkingDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
