AppBundle\Entity\Institution:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InstitutionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 200
            nullable: true
        description:
            type: text
            nullable: true
            length: 65535
        photoId:
            type: integer
            nullable: true
        imgUrl:
            type: string
            length: 200
            nullable: true
        owner:
            type: integer
        address:
            type: text
            nullable: true
        isActivated:
            type: integer
            nullable: true
        lat:
            type: float
            nullable: true
        lng:
            type: float
        categoryId:
            type: integer
            nullable: true
        recruitFrom:
            type: integer
            nullable: true
        recruitTo:
            type: integer
            nullable: true
    oneToMany:
        workingTime:
            targetEntity: WorkingHours
            mappedBy: institution
        phoneNumbers:
            targetEntity: PhoneNumber
            mappedBy: institution
    lifecycleCallbacks: {  }
