AppBundle\Entity\Suggestion:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SuggestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '200'
        imgUrl:
            type: string
            length: '200'
        isActive:
            type: boolean
            nullable: true
        url:
            type: 'string'
            length: '200'
    lifecycleCallbacks: {  }
