AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: '200'
            nullable: true
        lastName:
            type: string
            length: '200'
            nullable: true
        photoId:
            type: integer
            nullable: true
        smallPhotoUrl:
            type: string
            length: 200
            nullable: true
    lifecycleCallbacks: {  }